# Generated by Django 5.2.7 on 2025-10-24 20:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0004_customuser_alter_oeuvre_artiste'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualExhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_exhibitions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitionArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('oeuvre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.oeuvre')),
                ('virtual_exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='virtual_exhibitions.virtualexhibition')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('virtual_exhibition', 'oeuvre')},
            },
        ),
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('current_artwork_index', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('session_data', models.JSONField(blank=True, default=dict)),
                ('virtual_exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_sessions', to='virtual_exhibitions.virtualexhibition')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('virtual_exhibition', 'visitor')},
            },
        ),
    ]
