# Generated by Django 5.2.7 on 2025-10-26 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('theme', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expositions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='VirtualRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('room_type', models.CharField(choices=[('main', 'Main Hall'), ('gallery', 'Gallery Room'), ('special', 'Special Exhibition'), ('interactive', 'Interactive Space')], default='gallery', max_length=50)),
                ('position_order', models.PositiveIntegerField(default=0)),
                ('exposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='exposition.exposition')),
            ],
            options={
                'ordering': ['position_order'],
            },
        ),
        migrations.CreateModel(
            name='RoomArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('position_z', models.FloatField(default=0.0)),
                ('rotation_x', models.FloatField(default=0.0)),
                ('rotation_y', models.FloatField(default=0.0)),
                ('rotation_z', models.FloatField(default=0.0)),
                ('scale', models.FloatField(default=1.0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.artwork')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='exposition.virtualroom')),
            ],
            options={
                'unique_together': {('room', 'artwork')},
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('exposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='exposition.exposition')),
                ('rooms_visited', models.ManyToManyField(blank=True, to='exposition.virtualroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'exposition')},
            },
        ),
    ]
