# Generated by Django 5.2.6 on 2025-10-22 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='expositions/')),
            ],
            options={
                'verbose_name': 'Exposition',
                'verbose_name_plural': 'Expositions',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='SalleVirtuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('exposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='expositions.exposition')),
                ('oeuvres', models.ManyToManyField(blank=True, to='catalogue.oeuvre')),
            ],
            options={
                'verbose_name': 'Salle Virtuelle',
                'verbose_name_plural': 'Salles Virtuelles',
            },
        ),
    ]
