# Generated by Django 4.1 on 2025-10-22 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galeries', '0002_alter_collection_options_alter_galerie_options_and_more'),
        ('expositions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exposition',
            options={},
        ),
        migrations.RemoveField(
            model_name='exposition',
            name='image',
        ),
        migrations.RemoveField(
            model_name='exposition',
            name='titre',
        ),
        migrations.AddField(
            model_name='exposition',
            name='galerie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expositions', to='galeries.galerie'),
        ),
        migrations.AddField(
            model_name='exposition',
            name='nom',
            field=models.CharField(default='Exposition sans nom', max_length=200),
        ),
        migrations.DeleteModel(
            name='SalleVirtuelle',
        ),
    ]
