# Generated by Django 5.2.6 on 2025-10-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='galerie',
            options={},
        ),
        migrations.RemoveField(
            model_name='collection',
            name='active',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='galerie',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='galerie',
            name='date_creation',
        ),
        migrations.AddField(
            model_name='collection',
            name='est_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='galerie',
            name='description',
            field=models.TextField(),
        ),
    ]
