# Generated by Django 5.2.7 on 2025-10-24 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galeries', '0002_alter_collection_options_alter_galerie_options_and_more'),
        ('catalogue', '0004_customuser_alter_oeuvre_artiste'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Galerie',
            new_name='Gallery',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='galerie',
            new_name='gallery',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='est_active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='gallery',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_galleries', to='catalogue.customuser'),
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='nom',
            new_name='name',
        ),
        migrations.CreateModel(
            name='GalleryRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('layout', models.TextField(blank=True, help_text='JSON or text describing room layout')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='galeries.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='ArtworkPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('position_z', models.FloatField(default=0.0)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='catalogue.oeuvre')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='galeries.galleryroom')),
            ],
        ),
    ]
