# Generated by Django 5.2.7 on 2025-10-26 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_artist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='user',
        ),
    ]
