# Generated by Django 4.1 on 2025-10-22 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expositions', '0001_initial'),
        ('catalogue', '0002_auto_20251022_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('expositions', models.ManyToManyField(related_name='catalogues', to='expositions.exposition')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.TextField(blank=True, help_text='User preferences for art styles, themes, etc.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Artiste',
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='oeuvres',
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='couleur_principale',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='style',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='theme',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RemoveField(
            model_name='oeuvre',
            name='tags',
        ),
        migrations.AlterField(
            model_name='tag',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='viewed_oeuvres',
            field=models.ManyToManyField(blank=True, related_name='viewed_by', to='catalogue.oeuvre'),
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='oeuvres', to='catalogue.tag'),
        ),
    ]
