# Generated by Django 5.2.7 on 2025-10-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_customuser_alter_oeuvre_artiste'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeuvre',
            name='dimensions',
            field=models.CharField(blank=True, help_text='e.g., 100x200 cm', max_length=100),
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='location',
            field=models.CharField(blank=True, help_text='Current location or origin', max_length=200),
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='materials',
            field=models.CharField(blank=True, help_text='e.g., Oil on canvas', max_length=200),
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='technique',
            field=models.CharField(blank=True, help_text='e.g., Painting, Sculpture', max_length=100),
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='year_created',
            field=models.IntegerField(blank=True, help_text='Year the artwork was created', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_oeuvres',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='catalogue.oeuvre'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='search_history',
            field=models.JSONField(blank=True, default=list, help_text='List of recent searches'),
        ),
        migrations.CreateModel(
            name='ArtworkMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provenance', models.TextField(blank=True, help_text='History of ownership')),
                ('conservation_status', models.CharField(blank=True, help_text='e.g., Excellent, Good, Needs restoration', max_length=100)),
                ('exhibition_history', models.TextField(blank=True, help_text='Past exhibitions')),
                ('value_estimate', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated value in USD', max_digits=12, null=True)),
                ('copyright_info', models.TextField(blank=True, help_text='Copyright and usage rights')),
                ('additional_notes', models.TextField(blank=True)),
                ('oeuvre', models.OneToOneField(on_delete=models.CASCADE, related_name='metadata', to='catalogue.oeuvre')),
            ],
        ),
    ]
